<?php require('template/header.phtml') ?>
<script type="text/javascript">
    let userId = '<?php echo $_SESSION["userID"]; ?>';
</script>

<div class="row">
    <div class="col-md-9">
        <h3>Chat Messages</h3>
        <div class="chat-outer-area">
            <div class="chat-message-area">text area</div>
            <div class="col-md-6">
                <input class="chat-input" type="text" placeholder="Type your message here...">
                <button type="button" class="btn btn-primary">Send</button>
                <button type="button" class="btn btn-primary">Upload Image</button>
            </div>
        </div>
    </div>

    <div class="col-md-3 pull-right">
        <h3>Users</h3>
        <div class="user-chat-list">
            <button type="button" class="btn btn-primary" onclick="getChatUsers();">Display users</button>
<!--            <div onload="getChatUsers();">Display users</div>-->
            <div id="chat-user"></div>
<!--            --><?php //foreach ($users as $user){?>
<!--                <p>--><?php //echo $user->getFirstName(). " " .$user->getLastName()?><!--</p>-->
<!--            --><?php //}?>
        </div>
    </div>

</div>
<br>
<br>
<div><script src="Scripts/messaging.js" type="text/javascript" charset="utf-8"></script></div>
<?php require('template/footer.phtml') ?>