<?php require('template/header.phtml') ?>
<script type="text/javascript" charset="utf-8">
    let userId = '<?php echo $_SESSION["userID"]; ?>';
</script>

<body onload="getChatUsers(userId)">

    <div class="row">
        <div class="col-md-9">
            <h3>Chat Messages</h3>
            <div class="col-md-12">
<!--                <div id="timer" class="col-md-4"><br/></div>-->
                <div id="selected-user" class="col-md-3 pull-left"></div>
                <div id="timer" class="col-md-4"><br/></div>
                <div id="dots-container" class=" pull-left" style="">
                    <div id="dots-block" class="">
                        <div id="dots-single-dot" class=""></div>
                        <div id="dots-single-dot-2" class=""></div>
                        <div id="dots-single-dot-3" class=""></div>
                    </div>
                </div>

            </div>
            <div class="chat-outer-area">
                <div id="chat-message-display-area" class="chat-message-area"></div>
                <div class="col-md-6">
                    <input id="new-chat-message" class="chat-input" type="text" placeholder="Type your message here..." onkeyup="UserChatMessage.getMessageInput(this.value)">
                    <div class="col-md-9">
                        <form method="post" enctype="multipart/form-data">
                            <input type="file" name="files[]" multiple />
                            <input type="submit" value="Upload Image" name="submit" class="btn btn-info"/>
                        </form>
                        <button type="button" class="btn btn-primary" onclick="UserChatMessage.createNewMessage(userId)">Send</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3 pull-right">
            <div class="col-md-6">
                <h3>Users</h3>
            </div>
            <div class="col-md-6 pull-right">
                <div class="notification" onclick="getInboxCounter(userId)">
                    <span>Inbox</span>
                    <div id="inbox-counter-div" class="badge"><span id="inbox-counter"></span></div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="user-chat-list">
                    <div id="chat-user"></div>
                </div>
            </div>
        </div>

    </div>
    <br>
    <br>
    <div>

        <script src="Scripts/messaging.js" type="text/javascript" charset="utf-8"></script>

    </div>
</body>
<?php require('template/footer.phtml') ?>