<?php require('template/header.phtml') ?>
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<script src="https://kit.fontawesome.com/015b65f61b.js" crossorigin="anonymous"></script>

<div>
<!-- Search bar -->
<div class="row forum-top-bar">
        <div class="col-lg-1 col-xs-3 col-sm-2 col-md-2 logo "><h3>Forum</h3></div>
        <div class="col-lg-3 col-xs-9 col-sm-5 col-md-3">
            <div class="dropdown dropdown-position pull-right">
                <a class="link-text" data-toggle="dropdown" href="#">My Profile</a> <b class="caret"></b>
                <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">My Details</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-2" href="#">Inbox</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-3" href="#">Borderlands 3</a></li>
                </ul>
            </div>
        </div>

        <!-- Search box -->
        <div class="col-lg-4 search hidden-xs hidden-sm col-md-3">
            <div class="wrap search-box">
                <form action="#" method="post" class="form">
                    <div class="pull-left txt"><input type="text" class="form-control" placeholder="Search Posts">
                        <div class="pull-right search-icon"><button class="btn btn-success" type="button"><i class="fa fa-search"></i></button></div>
                    </div>
                </form>
            </div>
        </div>

        <!-- New post area -->
        <div class="col-lg-4 col-xs-12 col-sm-5 col-md-4 avt">
            <div class="start-topic pull-left">
                <form action="newPost.php" method="post" class="form">
                    <?php if(isset($_SESSION['userID'])) {?>
                    <button type="submit" class="btn btn-primary">Start New Post</button>
                    <?php } else {?>
                       <div class="col-xs-12 col-md-12">
                          <?php echo '<h5><a class="sign-in-message" href="signIn.php">Sign in</a> to post!</h5>';?>
                               </div>
                          <?php }?>
                    <!-- Button trigger modal -->
<!--                    --><?php //if(isset($_SESSION['userID'])) {?>
<!--                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">-->
<!--                        Start New Post-->
<!--                    </button>-->
<!---->
<!--                    <!- New Post Modal -->
<!--                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">-->
<!--                        <div class="modal-dialog" role="document">-->
<!--                            <div class="modal-content">-->
<!--                                <div class="modal-header">-->
<!--                                    <h3 class="modal-title" id="exampleModalLabel">New Post</h3>-->
<!--                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                                        <span aria-hidden="true">&times;</span>-->
<!--                                    </button>-->
<!--                                </div>-->
<!--                                <div class="modal-body">-->
<!--                                    <div class="container">-->
<!--                                            <div class="form-row">-->
<!--                                                <div class="col-md-7 mb-4">-->
<!--                                                    <label for="validationDefault01">Title</label>-->
<!--                                                    <input type="text" class="form-control" id="validationDefault01" name="title" required>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                            <div class="form-row">-->
<!--                                                <div class="form-group col-md-7 mb-4">-->
<!--                                                    <label for="inputState">Topic</label>-->
<!--                                                    <select id="inputState" class="form-control" name="topicSubject">-->
<!--                                                        --><?php //foreach ($topics as $topic){?>
<!--                                                        <option>-->
<!--                                                            --><?php
//                                                            echo $topic->getTopicSubject();
//                                                            $_POST['topicSubject'] = $topic;
//                                                            ?>
<!--                                                        </option>-->
<!--                                                        --><?php //}?>
<!--                                                    </select>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                            <div class="form-row">-->
<!--                                                <div class="col-md-7 mb-4">-->
<!--                                                    <label for="validationDefault03">Message</label>-->
<!--                                                    <textarea type="text" class="form-control" rows="3" name="postMessage" required></textarea>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                <div class="modal-footer">-->
<!--                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
<!--                                    <button type="submit" class="btn btn-primary">Create Post</button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                        <!- New Post Modal Ends -->
<!--                    --><?php //} else {?>
<!--                        <div class="col-xs-12 col-md-12">-->
<!--                            --><?php //echo '<h5><a class="sign-in-message" href="signIn.php">Sign in</a> to post!</h5>';?>
<!--                        </div>-->
<!--                    --><?php //}?>
                </form>
            </div>
            <div class="envelope pull-right"><i class="fa fa-envelope fa-3x"></i></div>

<!--            <div class="avatar pull-left dropdown">-->
<!--                <a data-toggle="dropdown" href="#"><img src="images/avatar.jpg" alt=""></a> <b class="caret"></b>-->
<!--                <div class="status green">&nbsp;</div>-->
<!--                <ul class="dropdown-menu" role="menu">-->
<!--                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">My Profile</a></li>-->
<!--                    <li role="presentation"><a role="menuitem" tabindex="-2" href="#">Inbox</a></li>-->
<!--                    <li role="presentation"><a role="menuitem" tabindex="-3" href="#">Log Out</a></li>-->
<!--                    <li role="presentation"><a role="menuitem" tabindex="-4" href="04_new_account.html">Create account</a></li>-->
<!--                </ul>-->
<!--            </div>-->

            <div class="clearfix"></div>
        </div>
</div>

<!-- Post area-->
<div class="col-lg-8 col-md-8 col-sm-12">
    <!-- DYNAMIC POST -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12 pull-left">
                <div id="post-layout">
                <?php foreach ($posts as $post){?>
                    <div class="col-md-8 col-sm-12 pull-left">
                        <h2><a><?php echo $post->getTitle()?></a></h2>
                        <p><?php echo $post->getPostMessage()?></p>
                    </div>
                    <div id="stats-position" class="col-md-4 col-sm-12 pull-left col-md-pull-1">
                        <div class="fas fa-user col-md-pull-8"><?php echo $post->getFirstName(). ' '.$post->getLastName()?></div>
                        <div class="far fa-address-card col-md-push-12">78 replies</div>
                        <div class="time col-md-pull-12"><i class="far fa-calendar-alt"></i><?php echo $post->getPostDate()?></div>
                    </div>
                <?php }?>
                </div>
            </div>
        </div>
    </div>
    <!-- Pagination -->
    <div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end pull-right">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="clearfix"></div>
</div>

    <!-- DYNAMIC POST -->




<!-- Categories -->
<div id="categories" class="col-lg-4 col-md-4 forum-layout">
    <div class="sidebarblock">
        <h3>Categories</h3>
        <div class="divline"></div>
        <div class="blocktxt">
            <ul class="cats">
                <li><a href="#">Countries<span class="badge pull-right">20</span></a></li>
                <li><a href="#">Regions<span class="badge pull-right">10</span></a></li>
                <li><a href="#">Red Wine<span class="badge pull-right">50</span></a></li>
                <li><a href="#">White Wine<span class="badge pull-right">36</span></a></li>
                <li><a href="#">Food Pairing<span class="badge pull-right">41</span></a></li>
            </ul>
        </div>
        <div class="start-topic pull-left">
            <form action="newCategory.php" method="post" class="form">
                <?php if($_SESSION['firstName'] == 'Admin'){?>
                    <button class="btn btn-primary">Start New Category</button>
                <?php }?>
            </form>
        </div>
    </div>
</div>

<!-- Topics -->
<div id="topics" class="col-lg-4 col-md-4 forum-layout">
    <div class="sidebarblock">
        <h3>Topics</h3>
        <div class="divline"></div>
        <div class="blocktxt">
            <ul class="cats">
                <li><a href="#">Red Wines <span class="badge pull-right">20</span></a></li>
                <li><a href="#">White Wines<span class="badge pull-right">10</span></a></li>
                <li><a href="#">Rose Wines <span class="badge pull-right">50</span></a></li>
                <li><a href="#">Wines By Country <span class="badge pull-right">36</span></a></li>
                <li><a href="#">French Wines<span class="badge pull-right">41</span></a></li>
                <li><a href="#">Italian Wines <span class="badge pull-right">11</span></a></li>
                <li><a href="#">New World Wines<span class="badge pull-right">5</span></a></li>
            </ul>
        </div>
        <div class="start-topic pull-left">
            <form action="newTopic.php" method="post" class="form">
                <?php if($_SESSION['firstName'] == 'Admin'){?>
                    <button class="btn btn-primary">Start New Topic</button>
                <?php }?>
            </form>
        </div>
    </div>
</div>


<?php require('template/footer.phtml') ?>
