<?php require('template/header.phtml') ?>
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<script src="https://kit.fontawesome.com/015b65f61b.js" crossorigin="anonymous"></script>

<div>
<!-- Search bar -->
<div class="row forum-top-bar">
        <div class="col-lg-1 col-xs-3 col-sm-2 col-md-2 logo "><h3>Posts</h3></div>
        <div class="col-lg-3 col-xs-9 col-sm-5 col-md-3">
            <div class="dropdown dropdown-position pull-right">
                <a class="link-text" data-toggle="dropdown" href="#">My Profile</a> <b class="caret"></b>
                <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">My Details</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-2" href="#">Inbox</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-3" href="#">Watchlist</a></li>
                </ul>
            </div>
        </div>

        <!-- Search box -->
        <div class="col-lg-4 search hidden-xs hidden-sm col-md-3">
            <div class="wrap search-box">
                <form action="forum.php" method="post" class="form">
                    <div class="pull-left txt">
                        <input type="text" class="form-control" placeholder="Search Posts" name="filter">
<!--                        <div class="pull-right search-icon"><button class="btn btn-success" type="submit"><i class="fa fa-search"></i></button></div>-->
                        <div class="pull-right search-icon"><button class="btn btn-success" type="submit"><img class="new-search" src="images/search-icon.png"></button></div>
                        <?php if($view->isFiltered) {?>
                        <button class="btn btn-group-justified" type="submit">Clear Search</button>
                        <?php }?>
                    </div>
                </form>
            </div>
        </div>

        <!-- New post area -->
        <div class="col-lg-4 col-xs-12 col-sm-5 col-md-4 avt">
            <div class="start-topic pull-left">
                <form action="newPost.php" method="post" class="form">
                    <?php if(isset($_SESSION['userID'])) {?>
                    <button type="submit" class="btn btn-primary">Start New Post</button>
                    <?php } else {?>
                       <div class="col-xs-12 col-md-12">
                          <?php echo '<h5><a class="sign-in-message" href="signIn.php">Sign in</a> to post!</h5>';?>
                               </div>
                          <?php }?>
                    <!-- Button trigger modal -->
<!--                    --><?php //if(isset($_SESSION['userID'])) {?>
<!--                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">-->
<!--                        Start New Post-->
<!--                    </button>-->
<!---->
<!--                    <!- New Post Modal -->
<!--                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">-->
<!--                        <div class="modal-dialog" role="document">-->
<!--                            <div class="modal-content">-->
<!--                                <div class="modal-header">-->
<!--                                    <h3 class="modal-title" id="exampleModalLabel">New Post</h3>-->
<!--                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                                        <span aria-hidden="true">&times;</span>-->
<!--                                    </button>-->
<!--                                </div>-->
<!--                                <div class="modal-body">-->
<!--                                    <div class="container">-->
<!--                                            <div class="form-row">-->
<!--                                                <div class="col-md-7 mb-4">-->
<!--                                                    <label for="validationDefault01">Title</label>-->
<!--                                                    <input type="text" class="form-control" id="validationDefault01" name="title" required>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                            <div class="form-row">-->
<!--                                                <div class="form-group col-md-7 mb-4">-->
<!--                                                    <label for="inputState">Topic</label>-->
<!--                                                    <select id="inputState" class="form-control" name="topicSubject">-->
<!--                                                        --><?php //foreach ($topics as $topic){?>
<!--                                                        <option>-->
<!--                                                            --><?php
//                                                            echo $topic->getTopicSubject();
//                                                            $_POST['topicSubject'] = $topic;
//                                                            ?>
<!--                                                        </option>-->
<!--                                                        --><?php //}?>
<!--                                                    </select>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                            <div class="form-row">-->
<!--                                                <div class="col-md-7 mb-4">-->
<!--                                                    <label for="validationDefault03">Message</label>-->
<!--                                                    <textarea type="text" class="form-control" rows="3" name="postMessage" required></textarea>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                <div class="modal-footer">-->
<!--                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
<!--                                    <button type="submit" class="btn btn-primary">Create Post</button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                        <!- New Post Modal Ends -->
<!--                    --><?php //} else {?>
<!--                        <div class="col-xs-12 col-md-12">-->
<!--                            --><?php //echo '<h5><a class="sign-in-message" href="signIn.php">Sign in</a> to post!</h5>';?>
<!--                        </div>-->
<!--                    --><?php //}?>
                </form>
            </div>
            <form action="#" method="post" class="form">
<!--                <div class="envelope pull-right"><button type="submit"><i class="fa fa-envelope fa-3x"></i></button></div>-->
                <div class="envelope pull-right"><button type="submit"><img class="mail-icon" src="images/mail.png"></button></div>

            </form>

            <div class="clearfix"></div>
        </div>
</div>

<!-- Post area-->
<div class="col-lg-8 col-md-8 col-sm-12">
    <!-- DYNAMIC POST -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12 pull-left">
                <div id="post-layout">
                <?php foreach ($posts as $post){?>
                    <div class="col-md-7 col-sm-12 pull-left">
                        <h2><a href="postReplies.php?postID=<?php echo $post->getID();?>&postingUser=<?php echo $post->getPostingUser();?>"><?php echo $post->getTitle()?></a></h2>
                        <p><?php echo $post->getMessage()?></p>
                    </div>
                    <div id="stats-position" class="col-md-3 col-sm-12 pull-left col-md-pull-1">
                        <?php if(isset($_SESSION['userID'])) {?>
                            <div class="col-md-pull-8">
                                <?php
                                $replyImage = $post->getImage();
                                $newImageData = base64_encode(file_get_contents($replyImage));
                                echo '<img src="data:image/jpeg;base64,'.$newImageData.'">';
                                ?>
                            </div>
                        <?php }?>
                        <div class="fas fa-user col-md-pull-8"><?php echo $post->getFirstName(). ' '.$post->getLastName()?></div>
<!--                        <div class="far fa-address-card col-md-push-12">78 replies</div>-->

                        <div class="row">
                        <div class="col-md-push-12">
<!--                            <div class="far fa-address-card col-md-push-12">78-->
                            <form action="forum.php" method="post" class="form">

                                <!-- ***** MODAL DEACTIVATED ***** Button trigger modal -->
                                <?php if(isset($_SESSION['userID'])) {?>
<!--                                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModal">replies</button>-->

                                    <!-- Reply Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>

                                                    <!-- Display the post again -->
                                                    <h3 class="modal-title" id="exampleModalLabel"><?php echo $post->getTitle()?></h3>
                                                    <h4><?php echo $post->getMessage()?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="container">

                                                        <div class="form-row">
                                                            <div class="form-group col-md-7 mb-4">
                                                                <?php foreach ($replies as $reply){?>
                                                                    <h4><?php echo $reply->getReplyMessage(); ?></h4>
                                                                    <h5><?php echo $reply->getReplyFrom(); ?></h5>
                                                                    <h5><?php echo $reply->getReplyDate(); ?></h5>
                                                                <?php }?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <a href="newReply.php?postingUser=<?php echo $post->getPostingUser();?>">Reply</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Reply Modal Ends -->

                                <?php } else {?>
                                    <div class="col-xs-12 col-md-12">
<!--                                        --><?php //echo '<h5><a class="sign-in-message" href="signIn.php">Sign in</a> to post!</h5>';?>
                                    </div>
                                <?php }?>
                            </form>
                        </div>
                        </div>
                        <div class="time col-md-pull-12"><i class="far fa-calendar-alt"></i><?php echo $post->getMessageDate()?></div>
                    </div>
                <?php }?>
                </div>
            </div>
        </div>
    </div>

    <!-- Pagination -->
    <div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end pull-right">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>

    <div>
        <?php
        // The "back" link
        $prevlink = ($page > 1) ? '<a href="?page=1" title="First page">&laquo;</a> <a href="?page=' . ($page - 1) . '" title="Previous page">&lsaquo;</a>' : '<span class="disabled">&laquo;</span> <span class="disabled">&lsaquo;</span>';

        // The "forward" link
        $nextlink = ($page < $pages) ? '<a href="?page=' . ($page + 1) . '" title="Next page">&rsaquo;</a> <a href="?page=' . $pages . '" title="Last page">&raquo;</a>' : '<span class="disabled">&rsaquo;</span> <span class="disabled">&raquo;</span>';

        // Display the paging information
        echo '<div id="paging"><p>', $prevlink, ' Page ', $page, ' of ', $pages, ' pages, displaying ', $start, '-', $end, ' of ', $total, ' results ', $nextlink, ' </p></div>';
        ?>

    </div>
    <div class="clearfix"></div>
</div>

<!-- Categories -->
<div id="categories" class="col-lg-4 col-md-4 forum-layout">
    <div class="sidebarblock">
        <h3>Categories</h3>
        <div class="divline"></div>
        <div class="blocktxt">
            <ul class="cats">
                <li><a href="#">Countries<span class="badge pull-right">20</span></a></li>
                <li><a href="#">Regions<span class="badge pull-right">10</span></a></li>
                <li><a href="#">Red Wine<span class="badge pull-right">50</span></a></li>
                <li><a href="#">White Wine<span class="badge pull-right">36</span></a></li>
                <li><a href="#">Food Pairing<span class="badge pull-right">41</span></a></li>
            </ul>
        </div>
        <div class="start-topic pull-left">
            <form action="newCategory.php" method="post" class="form">
                <?php if($_SESSION['firstName'] == 'Admin'){?>
                    <button class="btn btn-primary">Start New Category</button>
                <?php }?>
            </form>
        </div>
    </div>
</div>

<!-- Topics -->
<div id="topics" class="col-lg-4 col-md-4 forum-layout">
    <div class="sidebarblock">
        <h3>Topics</h3>
        <div class="divline"></div>
        <div class="blocktxt">
            <ul class="cats">
                <li><a href="#">Red Wines <span class="badge pull-right">20</span></a></li>
                <li><a href="#">White Wines<span class="badge pull-right">10</span></a></li>
                <li><a href="#">Rose Wines <span class="badge pull-right">50</span></a></li>
                <li><a href="#">Wines By Country <span class="badge pull-right">36</span></a></li>
                <li><a href="#">French Wines<span class="badge pull-right">41</span></a></li>
                <li><a href="#">Italian Wines <span class="badge pull-right">11</span></a></li>
                <li><a href="#">New World Wines<span class="badge pull-right">5</span></a></li>
            </ul>
        </div>
        <div class="start-topic pull-left">
            <form action="newTopic.php" method="post" class="form">
                <?php if($_SESSION['firstName'] == 'Admin'){?>
                    <button class="btn btn-primary">Start New Topic</button>
                <?php }?>
            </form>
        </div>
    </div>
</div>


<?php require('template/footer.phtml') ?>
