<?php require('template/header.phtml') ?>


<form name="reply-form" method="post" action="">
    <div class="container">

        <div id="msg-confirmation" class="row">
            <div class="reply-text col-md-4 mb-4 col-xs-6 pull-left">
                <h3>Inbox</h3>
            </div>

            <div class="reply-text col-md-4 mb-4 col-xs-6">
                <h3><a href="outbox.php">Outbox</a></h3>
            </div>

            <?php
            $deleteRand = rand();
            $_SESSION['delete-rand'] = $deleteRand;
            ?>
            <div class="col-md-4 col-xs-12">
                <button id="add-to-watchlist-button" type="submit" value="Submit" class="btn btn-primary delete-msg-button" name="delete-from-inbox">Delete message</button>
                <input type="hidden" value="<?php echo $deleteRand; ?>" name="delete-rand-check" />
            </div>
        </div>

        <div id="inbox-header" class="row">
            <div class="reply-text col-md-4 mb-4 col-xs-4 pull-left">
                <h4>Message</h4>
            </div>
            <div class="reply-text col-md-4 mb-4 col-xs-4">
                <h4>From</h4>
            </div>
            <div class="reply-text col-md-4 mb-4 col-xs-4">
                <h4>Date</h4>
            </div>
        </div>

        <div class="row">
            <div id="post-layout" class="col-md-12 col-xs-12 pull-left">
                <?php foreach ($inbox as $i){?>
                    <div class="col-md-6 col-xs-7">
                        <input id="del-checkbox-position" type="checkbox" name="id[]" value="<?php echo $i->getMessageID()?>" class="pull-left"/>
                        <input type="hidden" name="getMessageID" value="<?php echo $i->getMessageID()?>"/>
                        <h5><?php echo $i->getMessage(); ?></h5>
                    </div>

                    <div class="col-md-3 col-xs-2">
                        <h5 id="user-name-position" class=""><?php echo $i->getFirstName() . ' '. $i->getLastName(); ?></h5>
                    </div>

                    <div class="col-md-3 col-xs-2">
                        <h5 id="user-name-position" class=""><?php echo $i->getMessageDate(); ?></h5>
                    </div>

                <?php }?>
            </div>
        </div>
    </div>
</form>
<br>

<?php require('template/footer.phtml') ?>
