<?php require('template/header.phtml') ?>

<div class="container ">
    <div class="home-text">
        <div class="row col-lg-12 col-md-12 col-xs-12">
            <h3>Welcome to the Salford Medication Forum!</h3>
        </div>
        <div class="row col-lg-12 col-md-12 col-xs-12">
            <h5>This is a place dedicated for discussion on available drug treatments on several diseases.</h5>
            <h5>Here you can make questions, find support and guidance about the alternatives of any condition. Feel free to sign up and start posting!</h5>
        </div>
    </div>

    <div class="row col-lg-12 col-md-12 col-xs-12">
        <div class="col-lg-3 col-md-3 col-xs-3"></div>
        <!-- Categories -->
        <div id="categories" class="col-lg-6 col-md-6 forum-layout">
            <div class="sidebarblock">
                <h3>Categories</h3>
                <div class="divline"></div>
                <div class="blocktxt">
                    <?php foreach ($categories as $category){?>
                        <ul class="cats">
                            <li><?php echo $category->getCategoryName()?></li>
                        </ul>
                    <?php }?>
                </div>
                <div class="start-topic pull-left">
                    <form action="newCategory.php" method="post" class="form">
                        <?php if($_SESSION['isAdmin'] == 1){?>
                            <button class="btn btn-primary">Start New Category</button>
                        <?php }?>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-3"></div>
    </div>

        <div class="row col-lg-12 col-md-12 col-xs-12">
            <div class="col-lg-3 col-md-3 col-xs-3"></div>
            <!-- Topics -->
            <div id="topics" class="col-lg-6 col-md-6 forum-layout">
                <div class="sidebarblock">
                    <h3>Topics</h3>
                    <div class="divline"></div>
                    <div class="blocktxt">
                        <?php foreach ($topics as $topic){?>
                            <ul class="cats">
                                <li><?php echo $topic->getTopicSubject()?> <span class="badge"><?php echo $topicDataSet->getPostCountByTopicId($topic->getTopicID());?></span></li>
                            </ul>
                        <?php }?>
                    </div>
                    <div class="start-topic pull-left">
                        <form action="newTopic.php" method="post" class="form">
                            <?php if($_SESSION['isAdmin'] == 1){?>
                                <button class="btn btn-primary">Start New Topic</button>
                            <?php }?>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3"></div>
        </div>
    </div>
    <br>
</div>

<?php require('template/footer.phtml') ?>
