<?php require('template/header.phtml') ?>

<form name="reply-form" method="post" action="">
    <?php
    $rand = rand();
    $_SESSION['rand'] = $rand;
    ?>

    <div class="container">

        <div id="msg-confirmation" class="row">
            <div class="reply-text col-md-8 mb-4 col-xs-12 pull-left">
                <h3>Message this user</h3>
            </div>
            <?php if($view->isMessageSent){?>
            <div class="reply-text col-md-4 mb-4 col-xs-12">
                <h4>Your message has been sent!</h4>
            </div>
            <?php }?>

            <?php if($view->wrongLenght){?>
                <div class="reply-text col-md-4 mb-4 col-xs-12">
                    <h4>Max 300 characters!</h4>
                </div>
            <?php }?>
        </div>
        <div class="row">
            <div class="col-md-1 hidden-xs hidden-sm"></div>
            <div class="reply-text col-md-10 mb-4 col-xs-12 pull-left">
                <textarea name="contact" placeholder="Type your message here..." rows="5" required></textarea>
            </div>
            <div class="col-md-1 hidden-xs hidden-sm"></div>
        </div>

        <div class="row">
            <div class="col-md-1 hidden-xs hidden-sm"></div>
            <div class="col-md-10 mb-4 col-xs-12 pull-left">
                <button type="submit" value="Submit" class="btn btn-primary">Send</button>
                <input type="hidden" value="<?php echo $rand; ?>" name="rand-check" />
            </div>
            <div class="col-md-1 hidden-xs hidden-sm"></div>
        </div>
    </div>
    <br>
</form>

<?php require('template/footer.phtml') ?>
