<?php require('template/header.phtml') ?>

<h3>Reply to this post</h3>

<form name="reply-form" method="post" >
    <input type="hidden" >
    <div class="container">
         <div class="row">
            <div class="reply-text col-md-12 mb-4">
                <textarea name="reply" rows="5"></textarea>
            </div>
         </div>

        <div class="row col-md-12 mb-4">
            <button type="submit"  class="btn btn-primary">Reply</button>
        </div>
    </div>
</form>

<div class="fas fa-arrow-alt-circle-left">
    <h3>Back to all the <a href="forum.php">posts</a>.</h3><br>
</div>

<?php require('template/footer.phtml') ?>
