<?php require('template/header.phtml'); ?>

<div class="container">
    <h3>New Topic</h3>
        <form name="topic-form" method="post" action="newTopic.php">
            <div class="form-row">
                <div class="col-md-6 mb-4">
                    <label for="validationDefault01">Subject</label>
                    <input type="text" class="form-control" id="validationDefault01" name="subject" required>
                </div>

                <div class="form-group col-md-6 mb-4">
                        <label for="inputState">Category</label>
                        <select id="inputState" class="form-control" name="category">
                            <?php foreach ($categories as $category){?>
                            <option>
                                <?php
                                 echo $category->getCategoryName();
                                ?>
                            </option>
                            <?php }?>
                        </select>
                </div>
            </div>

            <div class="form-row">
                <div class="col-md-12 mb-4">
                    <label for="validationDefault03">Description</label>
                    <input type="text" class="form-control" name="description" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-8 mb-3 spacing">
                    <button class="btn btn-primary" type="submit">Create Topic</button>
                </div>
            </div>
        </form>
</div>
<?php if($view->isTopicCreated) {
    echo '<h3> Topic created! Create another one or click <a href="forum.php">here</a> to go back to the forum.</h3><br>';
}?>


<?php require('template/footer.phtml') ?>


