<?php require('template/header.phtml'); ?>

<div class="container">
    <h3>New Topic</h3>
        <form name="topic-form" method="post" action="newTopic.php">
            <div class="form-row">
                <div class="col-md-6 mb-4">
                    <label for="validationDefault01">Subject</label>
                    <input type="text" class="form-control" id="validationDefault01" name="topicSubject" required>
                </div>
                <div class="form-group col-md-6 mb-4">
                    <label for="inputState">Category</label>
                    <select id="inputState" class="form-control">
                        <option selected>Choose...</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-12 mb-4">
                    <label for="validationDefault03">Description</label>
                    <input type="text" class="form-control" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-8 mb-3 spacing">
                    <button class="btn btn-primary" type="submit">Create Topic</button>
                </div>
            </div>

        </form>
</div>

<?php require('template/footer.phtml') ?>


