<?php require('template/header.phtml'); ?>

<div class="container">
    <h3>New Topic</h3>
        <form name="topic-form" method="post" action="newTopic.php"> <!--**** change to forum.php ***** -->
            <div class="form-row">
                <div class="col-md-6 mb-4">
                    <label for="validationDefault01">Subject</label>
                    <input type="text" class="form-control" id="validationDefault01" name="subject" required>
                </div>

                <div class="form-group col-md-6 mb-4">
                    <label for="inputState">Category</label>
                    <select id="inputState" class="form-control" name="category">
                        <option>Countries</option>
                        <option>Regions</option>
                        <option>Red Wine</option>
                        <option>White Wine</option>
                        <option>Food Pairing</option>
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="col-md-12 mb-4">
                    <label for="validationDefault03">Description</label>
                    <input type="text" class="form-control" name="description" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-8 mb-3 spacing">
                    <button class="btn btn-primary" type="submit">Create Topic</button>
                </div>
            </div>

        </form>
</div>

<?php require('template/footer.phtml') ?>


