<?php require('template/header.phtml') ?>


<form name="outbox-form" method="post" action="">
    <div class="container">

        <div id="msg-confirmation" class="row">
            <div class="reply-text col-md-4 mb-4 col-xs-6 pull-left">
                <h3>Outbox</h3>
            </div>

            <div class="reply-text col-md-4 mb-4 col-xs-6">
                <h3><a href="inbox.php">Inbox</a></h3>
            </div>

            <?php
            $deleteRand = rand();
            $_SESSION['delete-rand'] = $deleteRand;
            ?>
            <div class="col-md-4 col-xs-12">
                <button id="add-to-watchlist-button" type="submit" value="Submit" class="btn btn-primary delete-msg-button" name="delete-from-inbox">Delete message</button>
                <input type="hidden" value="<?php echo $deleteRand; ?>" name="delete-rand-check" />
            </div>
        </div>

        <div id="inbox-header" class="row">
            <div class="header-text col-md-7 mb-4 col-xs-6 pull-left">
                <h4>Message</h4>
            </div>
            <div class="header-text col-md-2 mb-4 col-xs-3">
                <h4>To</h4>
            </div>
            <div class="header-text col-md-3 mb-4 col-xs-2">
                <h4>Date</h4>
            </div>
        </div>

        <div class="row">
            <div id="post-layout" class="col-md-12 col-xs-12 pull-left">
                <?php foreach ($outbox as $o){?>
                    <div class="col-md-7 col-xs-7">
                        <div class="">
                            <input id="del-checkbox-position" type="checkbox" name="id[]" value="<?php echo $o->getMboxID()?>" class="pull-left"/>
                            <input type="hidden" name="getMboxID" value="<?php echo $o->getMboxID()?>"/>
                        </div>
                        <div class="text-message">
                            <h5><?php echo $o->getMessage(); ?></h5>
                        </div>
                    </div>

                    <div class="col-md-2 col-xs-2">
                        <h5 class=""><?php echo $o->getFirstName() . ' '. $o->getLastName(); ?></h5>
                    </div>

                    <div class="col-md-3 col-xs-2">
                        <h5 class=""><?php echo $o->getMessageDate(); ?></h5>
                    </div>
                    <div class="text-message-bottom col-md-12 col-xs-12"></div>
                <?php }?>
            </div>
        </div>
        <div class="row">
            <?php if (empty($outbox)){?>
                <div class="error-message">
                    <h4>Your outbox is empty!</h4>
                </div>
            <?php }?>
        </div>
    </div>
</form>
<br>

<?php require('template/footer.phtml') ?>
