<?php require('template/header.phtml'); ?>

<div class="container">
    <h3>Password reset</h3>
    <div class="row">
        <div class="col-md-3 col-xs-1"></div>

            <div class="user-layout col-md-6 col-xs-6">
                <form name="user-form" method="post" action="">
                    <?php
                    $rand = rand();
                    $_SESSION['rand'] = $rand;
                    ?>
                    <div class="spacing">
                        <label>Old Password:</label>
                        <input type="password" name="old-password" required>
                    </div>
                    <div class="spacing">
                        <label>New Password:</label>
                        <input type="password" name="new-password" required>
                    </div>
                    <div class="spacing">
                        <label>Re-type New Password:</label>
                        <input type="password" name="re-typed-password" required>
                    </div>
                    <div class="error-message">
                        <?php
                        if (!empty($errors) && isset($_POST['new-password'])){
                            echo '<h5>' . $errors . '</h5>';
                        }
                        ?>
                    </div>

                    <div class="error-message">
                        <?php if($view->loginError) {echo "Password incorrect.";}?>
                    </div>
                    <div class="text-success">
                        <?php if($view->isInfoUpdated) {echo "Password successfully updated!";}?>
                    </div>
                    <div class="spacing">
                        <input type="submit" name="update" value="Update" class="btn btn-primary">
                        <input type="hidden" value="<?php echo $rand; ?>" name="rand-check" />
                    </div>
                </form>
            </div>
            <div class="col-md-2 col-xs-2"></div>
    </div>
</div>
<br>
<?php require('template/footer.phtml') ?>
