<?php require('template/header.phtml')?>

    <div>
    <?php

    if(isset($view->message)){
            echo $view->message;
    }
    elseif (isset($_COOKIE['first']) && isset($_COOKIE['second'])) {
        echo $view->cookieMessage;
        echo "<h2>Welcome " .$_COOKIE['first']. '  ' . "DOB: " .$_COOKIE['second']."</h2>";

    }
    else{?>
        <h2><strong>Please enter your details below:</strong></h2>

        <form name="form1" method="post" action="persistence.php">
            <div class="spacing">
                <label>Your name:</label>
                <input type="text" name="name">
            </div>

            <div class="spacing">
                <label>Your Birthday (in DD/MM/YYYY format):</label>
                <input type="text" name="birthday">
            </div>

            <div class="spacing">
                <input type="submit" name="Submit" value="Submit">
                <input type="reset" name="Submit2" value="Reset">
            </div>
        </form>
        </div>
    <?php } ?>


<?php require('template/footer.phtml') ?>