<?php require('template/header.phtml') ?>
<script src="https://kit.fontawesome.com/015b65f61b.js" crossorigin="anonymous"></script>

<!-- VERSION 1 - re-directs to newReply.php -->

<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div id="post-layout" class="col-md-6 col-xs-12 pull-left">-->
<!--            --><?php //foreach ($post as $p){?>
<!--                <h3>--><?php //echo $p->getTitle(); ?><!--</h3>-->
<!--                <h4>--><?php //echo $p->getMessage(); ?><!--</h4>-->
<!--                <h5 class="fas fa-user col-md-12">--><?php //echo $p->getFirstName() . ' '. $p->getLastName(); ?><!--</h5>-->
<!---->
<!--                --><?php //if(empty($replies)) {?>
<!--                    <div class="row pull-right">-->
<!--                        <a href="newReply.php?replyFrom=--><?php //echo $_SESSION['userID'];?><!--&replyTo=--><?php //echo $p->getPostingUser();?><!--&postID=--><?php //echo $p->getID();?><!--">Reply</a>-->
<!--                    </div>-->
<!--                --><?php //}?>
<!--            --><?php //}?>
<!--        </div>-->
<!---->
<!--        --><?php //if(!empty($replies)) {?>
<!--            <div id="reply-layout" class="col-md-5 mb-4">-->
<!--                --><?php //foreach ($replies as $reply){?>
<!--                    <h4>--><?php //echo $reply->getReplyMessage(); ?><!--</h4>-->
<!--                    <h5 class="fas fa-user col-md-12">--><?php //echo $reply->getReplierFirstName() . ' '. $reply->getReplierLastName(); ?><!--</h5>-->
<!--                    <h5 class="far fa-calendar-alt col-md-12">--><?php //echo $reply->getReplyDate(); ?><!--</h5>-->
<!--                    <div class="bottom-message">-->
<!--                        <a href="newReply.php?replyFrom=--><?php //echo $reply->getReplyFrom();?><!--&replyTo=--><?php //echo $reply->getReplyTo();?><!--&postID=--><?php //echo $postID;?><!--">Reply</a>-->
<!--                    </div>-->
<!--                --><?php //}?>
<!--            </div>-->
<!--        --><?php //}?>
<!--    </div>-->
<!--</div>-->


<!-- VERSION 2 - reply inside this page using form -->

<form name="reply-form" method="post" action="">
    <div class="container">
        <div class="row">
            <div id="post-layout" class="col-md-12 col-xs-12 pull-left">
                <?php foreach ($post as $p){?>
                    <h3><?php echo $p->getTitle(); ?></h3>
                    <h4><?php echo $p->getMessage(); ?></h4>
                    <div class="col-md-1 col-xs-2">
                        <?php
                        $replyImage = $p->getImage();
                        $newImageData = base64_encode(file_get_contents($replyImage));
                        echo '<img src="data:image/jpeg;base64,'.$newImageData.'">';
                        ?>
                    </div>
                    <h5 id="user-name-position" class="fas fa-user col-md-11 pull-left"><?php echo $p->getFirstName() . ' '. $p->getLastName(); ?></h5>

                    <?php
                    $rand = rand();
                    $_SESSION['rand'] = $rand;
                    ?>

                    <?php if(!empty($replies)) {?>
                        <div id="reply-layout" class="col-md-12 mb-4">
                            <?php foreach ($replies as $reply){?>
                                <h4><?php echo $reply->getReplyMessage(); ?></h4>
                                <div class="col-md-1 col-xs-2 pull-right">
                                    <?php
                                    $replyImage = $reply->getReplyImage();
                                    $newImageData = base64_encode(file_get_contents($replyImage));
                                    echo '<img src="data:image/jpeg;base64,'.$newImageData.'">';
                                    ?>
                                </div>
                                <h5 class="fas fa-user col-md-11"><?php echo $reply->getReplierFirstName() . ' '. $reply->getReplierLastName(); ?></h5>
                                <h5 class="far fa-calendar-alt col-md-12 bottom-message"><?php echo $reply->getReplyDate(); ?></h5>
                            <?php }?>
                        </div>
                    <?php }?>

                    <!-- REPLY BUTTON -->
                    <div class="container">
                        <div class="row">
                            <div class="reply-text col-md-12 mb-4 col-xs-12 pull-left">
                                <h4>Reply to this post</h4>
                                <textarea name="reply" rows="5"></textarea>
                            </div>
                        </div>

                        <div class="row col-md-12 mb-4 col-xs-12 pull-left">
                            <button type="submit" value="Submit" class="btn btn-primary">Reply</button>
                            <input type="hidden" value="<?php echo $rand; ?>" name="rand-check" />
                            <input type="hidden" name="getUserID" value="<?php echo $_SESSION['userID']?>"/>
                            <input type="hidden" name="getPostingUser" value="<?php echo $p->getPostingUser()?>"/>
                            <input type="hidden" name="getID" value="<?php echo $p->getID()?>"/>
                        </div>
                    </div>
                <?php }?>
            </div>
        </div>
    </div>
</form>


<div>
    <h3>Back to all the <a href="forum.php">posts</a>.</h3><br>
</div>


<?php require('template/footer.phtml') ?>

