<?php require('template/header.phtml') ?>
<!--<script src="https://kit.fontawesome.com/015b65f61b.js" crossorigin="anonymous"></script>-->

<form name="reply-form" method="post" action="">
    <div class="container">
        <div class="row">
            <div id="post-layout" class="col-md-12 col-xs-12 pull-left">
                <?php foreach ($post as $p){?>
                    <h3><?php echo $p->getTitle(); ?></h3>
                    <h4><?php echo $p->getMessage(); ?></h4>
                    <div class="col-md-1 col-xs-2">
                        <?php if (isset($_SESSION['userID'])) {
                            $replyImage = $p->getImage();
                            $newImageData = base64_encode(file_get_contents($replyImage));
                            echo '<img src="data:image/jpeg;base64,' . $newImageData . '">';
                        }?>
                    </div>
                    <?php
                    $watchlistRand = rand();
                    $_SESSION['watchlist-rand'] = $watchlistRand;
                    ?>
                    <div class="col-md-11">
                        <div class="col-md-9 col-xs-4 pull-left">
                            <h5 id="user-name-position"><span class="glyphicon glyphicon-user"><strong><?php echo $p->getFirstName() . ' '. $p->getLastName(); ?></strong></h5>
                        </div>
                        <div class="col-md-2 col-xs-2">
                            <?php if (isset($_SESSION['userID'])) {?>
                                <?php if(!$view->isInWatchlist) {?>
                                <button id="add-to-watchlist-button" type="submit" value="Submit" class="btn btn-primary" name="add-to-watchlist">Add to watchlist</button>
                                    <input type="hidden" value="<?php echo $watchlistRand; ?>" name="watchlist-rand-check" />
                                <?php } else {?>
                                <button id="add-to-watchlist-button" type="submit" value="Submit" class="btn btn-primary" name="remove-from-watchlist">Remove from watchlist</button>
                                <input type="hidden" value="<?php echo $watchlistRand; ?>" name="watchlist-rand-check" />
                                <?php }?>
                            <?php }?>
                        </div>
                    </div>

                    <?php
                    $rand = rand();
                    $_SESSION['rand'] = $rand;
                    ?>

                    <?php if(!empty($replies)) {?>
                        <div id="reply-layout" class="col-md-12 mb-4">
                            <?php foreach ($replies as $reply){?>
                                <h4><?php echo $reply->getReplyMessage(); ?></h4>
                                <div class="row">
                                    <div class="col-md-12 col-xs-12 pull-right">
                                        <?php if (isset($_SESSION['userID'])) {
                                            $replyImage = $reply->getReplyImage();
                                            $newImageData = base64_encode(file_get_contents($replyImage));
                                            echo '<img src="data:image/jpeg;base64,' . $newImageData . '">';
                                        }?>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 col-xs-12 pull-right">
                                        <div class="replier-username">
                                            <h5 class=""><span class="glyphicon glyphicon-user"><strong><?php echo $reply->getReplierFirstName() . ' '. $reply->getReplierLastName(); ?></strong></h5>
                                        </div>
                                        <div class="reply-date">
                                            <h5 class="bottom-message"><span class="glyphicon glyphicon-calendar"><strong><?php echo $reply->getReplyDate(); ?></strong></h5>
                                        </div>
                                    </div>
                                </div>
                            <?php }?>
                        </div>
                    <?php }?>

                    <?php if(isset($_SESSION['userID'])){?>
                    <!-- REPLY BUTTON -->
                    <div class="container">
                        <div class="row">
                            <div class="reply-text col-md-12 mb-4 col-xs-12 pull-left">
                                <textarea name="reply" placeholder="Reply to this post (max of 300 characters)" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="row col-md-12 mb-4 col-xs-12 pull-left">
                                <button type="submit" value="Submit" class="btn btn-primary">Reply</button>
                                <input type="hidden" value="<?php echo $rand; ?>" name="rand-check" />
                                <input type="hidden" name="getUserID" value="<?php echo $_SESSION['userID']?>"/>
                                <input type="hidden" name="getPostingUser" value="<?php echo $p->getPostingUser()?>"/>
                                <input type="hidden" name="getID" value="<?php echo $p->getID()?>"/>
                        </div>

                        <div class="row col-md-12 mb-4 col-xs-12 pull-left">
                            <?php if($view->isWrongLimit){?>
                                <div class="error-message">
                                    <h5>Max 300 characters!</h5>
                                </div>
                            <?php }?>
                        </div>
                    </div>
                    <?php } else {?>
                        <div class="row">
                            <div class="reply-text col-md-12 mb-4 col-xs-12 pull-left">
                                <h4><a href="signIn.php">Sign in</a> to reply.</h4><br>
                            </div>
                        </div>
                    <?php }?>
                <?php }?>
            </div>
        </div>
    </div>
</form>
<br>
<?php require('template/footer.phtml') ?>

