
    <div class="container">
        <h3><strong>Products list</strong></h3>
        <table>
            <tr>
                <th>Item</th>
                <th>Description</th>
                <th>Cost</th>
                <th>Click to buy</th>
            </tr>

            <?php
            foreach ($products as $product) {?>
                <tr>
                    <td><?php echo $product['name']?></td>
                    <td><?php echo $product['description']?></td>
                    <td><?php echo $product['price']?></td>
                    <form method="post" action="shop.php">
                        <th><button type="submit" name ="productItem" class="btn btn-primary"/>Buy</th>
                        <input type="hidden" name="item" value="<?php echo $product['name']. ' at ' .$product['price']?>"/>
                    </form>
                </tr>
            <?php } ?>
        </table>
    </div>
    <br>


