<?php require('template/header.phtml') ?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>

<?php if(!$view->isRegistered){?>
<h3>Register here to post</h3>

<form name="register-form" method="post" action="registerUser.php">
    <div class="spacing">
        <label>First name:</label>
        <input type="text" name="firstName" required>
    </div>
    <div class="spacing">
        <label>Last name:</label>
        <input type="text" name="lastName" required>
    </div>
    <div class="spacing">
        <label>Email:</label>
        <input type="text" name="email" required>
    </div>

    <div class="spacing">
        <label>Password:</label>
        <input type="password" name="password" required>
    </div>
    <div class="spacing">
        <label>Re-enter password:</label>
        <input type="password" name="re-typed-password" required>
    </div>
    <div class="error-message">
        <?php
        if (!empty($errors) && isset($_POST['password'])){
            echo '<h4>' . $errors . '</h4>';
        }
        ?>
    </div>

    <div class="spacing">
        <!-- Captcha input -->
        <div class="g-recaptcha" data-sitekey="6LfrJcUUAAAAACPjTF0S_S2259YM646wWN1JjZbC"></div>
        <br/>
        <input type="submit" name="register" value="Register" class="btn btn-success">
    </div>

</form>
<?php } else if($view->isRegistered) {

    echo '<h3> Welcome '.$_SESSION['firstName']. ' '.$_SESSION['lastName']. '! Click <a href="forum.php">here</a> to post.</h3>';

}?>

<?php require('template/footer.phtml') ?>
