<?php require('template/header.phtml') ?>

<h3>Register here to post</h3>

<form name="form1" method="post" action="signIn.php">
    <div class="spacing">
        <label>First name</label>
        <input type="text" name="email">
    </div>
    <div class="spacing">
        <label>Last name</label>
        <input type="text" name="email">
    </div>
    <div class="spacing">
        <label>Email</label>
        <input type="text" name="email">
    </div>

    <div class="spacing">
        <label>Password</label>
        <input type="password" name="password">
    </div>

    <div class="spacing">
        <label>Re-enter password</label>
        <input type="password" name="password">
    </div>
    <div class="spacing">
        <label>Select image (optional):</label>
        <input type="file" name="photo" value="Choose file" class="btn btn-primary btn-sm">
    </div>

    <div class="spacing">
        <input type="submit" name="register" value="Register" class="btn btn-success">
    </div>
</form>


<?php require('template/footer.phtml') ?>
