<?php require('template/header.phtml'); ?>

<h3><strong>Sign in to post</strong></h3>
<h5> ( Do not have an account? Register <a href="registerUser.php">here</a>. )</h5>

<form name="signIn-form" method="post" action="signIn.php">
    <div class="spacing">
        <label>Email:</label>
        <input type="text" name="email">
    </div>

    <div class="spacing">
        <label>Password:</label>
        <input type="password" name="password">
    </div>

    <div class="spacing">
        <input type="submit" name="signIn" value="Sign In" class="btn btn-success">
    </div>
</form>

<?php require('template/footer.phtml') ?>