<?php require('template/header.phtml'); ?>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

<div class="container">
    <?php if(!$view->isLogged && $_SESSION['signed_in'] == false){?>
        <div class="row">
            <div class="col-md-3 col-lg-3 hidden-xs hidden-sm"></div>
            <div class="col-md-8 col-lg-8 col-xs-12 col-sm-12">
                <h3><strong>Sign in to post</strong></h3>
                <h5> ( Do not have an account? Register <a href="registerUser.php">here</a>. )</h5>

                <form class="user-layout" name="signIn-form" method="post" action="signIn.php">
                    <div class="spacing">
                        <label>Email:</label>
                        <input type="text" name="email" required>
                    </div>

                    <div class="spacing">
                        <label>Password:</label>
                        <input type="password" name="password" required>
                    </div>
                    <div class="error-message">
                        <?php if($view->loginError) {echo "Email and password do not match";}?>
                    </div>
                    <div class="spacing">

                        <!-- Captcha input -->
                        <div class="g-recaptcha" data-sitekey="6LfrJcUUAAAAACPjTF0S_S2259YM646wWN1JjZbC"></div>
                        <br/>
                        <input type="submit" name="signIn" value="Sign In" class="btn btn-success">
                    </div>
                </form>
            </div>
            <div class="col-md-2 col-lg-2 hidden-xs hidden-sm"></div>
        </div>
    <?php } else if($view->isLogged || $_SESSION['signed_in']) {
        echo '<h3> Welcome '.$_SESSION['firstName']. ' '.$_SESSION['lastName']. '! Click <a href="forum.php">here</a> to post.</h3>';
    }?>
</div>
<?php require('template/footer.phtml') ?>