<?php require('template/header.phtml'); ?>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>


<?php if(!$view->isLogged){?>
<h3><strong>Sign in to post</strong></h3>
<h5> ( Do not have an account? Register <a href="registerUser.php">here</a>. )</h5>

<form name="signIn-form" method="post" action="signIn.php">
    <div class="spacing">
        <label>Email:</label>
        <input type="text" name="email">
    </div>

    <div class="spacing">
        <label>Password:</label>
        <input type="password" name="password">
    </div>
    <div class="error-message">
        <?php if($view->loginError) {echo "Email and password do not match";}?>
    </div>
    <div class="spacing">

        <!-- Captcha input -->
        <div class="g-recaptcha" data-sitekey="6LfrJcUUAAAAACPjTF0S_S2259YM646wWN1JjZbC"></div>
        <br/>
        <input type="submit" name="signIn" value="Sign In" class="btn btn-success">
    </div>

</form>
<?php } else if($view->isLogged) {
    echo '<h3> Welcome '.$_SESSION['firstName']. ' '.$_SESSION['lastName']. '! Click <a href="forum.php">here</a> to post.</h3>';
}?>

<?php require('template/footer.phtml') ?>