<?php require('template/header.phtml') ?>

<form name="reply-form" method="post" action="">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-7 col-xs-5">
                <h3>Watchlist</h3>
            </div>

            <?php
            $removeRand = rand();
            $_SESSION['unsubscribe-rand'] = $removeRand;
            ?>
            <div class="col-md-3 col-xs-2">
                <button id="add-to-watchlist-button" type="submit" value="Submit" class="btn btn-primary" name="remove-from-watchlist">Remove from watchlist</button>
                <input type="hidden" value="<?php echo $removeRand; ?>" name="remove-rand-check" />
            </div>

        </div>

        <div class="row">
            <div id="post-layout" class="watchlist-text col-md-12 col-xs-12 pull-left">
                <?php foreach ($subscribedPosts as $sp){?>
                    <div class="col-md-7 col-sm-7 col-xs-9">
                        <input id="checkbox-position" type="checkbox" name="id[]" value="<?php echo $sp->getSubPostID()?>" class="pull-left"/>
                        <input type="hidden" name="getSubPostID" value="<?php echo $sp->getSubPostID()?>"/>
                        <h3><?php echo $sp->getTitle(); ?></h3>
                        <p><?php echo $sp->getMessage(); ?></p>
                    </div>

                    <div class="col-md-3 col-sm-5 col-xs-12">
                        <div id="watchlist-user" class="row col-md-12">
                            <h5 id="user-name-position"><span class="glyphicon glyphicon-user"><strong><?php echo $sp->getFirstName() . ' '. $sp->getLastName(); ?></strong></h5>
                        </div>
                    </div>
                <?php }?>
            </div>
        </div>

        <div class="row">
            <?php if (empty($subscribedPosts)){?>
                <div class="error-message">
                    <h4>Your watchlist is empty!</h4>
                </div>
            <?php }?>
        </div>
    </div>
</form>
    <br>
<?php require('template/footer.phtml') ?>