<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Salford Wine Forum - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container">

    <div class="row">

        <!-- NAVBAR -->
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Salford Meds Forum</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <div id="hover-link">
                        <ul class="nav navbar-nav">
                            <li><a href="index.php">Home</a></li>
                            <li><a href="forum.php">Forum</a></li>
                            <?php if (isset($_SESSION['signed_in'])) {?>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown">My Profile
                                        <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">My Info</a></li>
                                        <li><a href="watchList.php">Watchlist</a></li>
                                    </ul>
                                </li>
                            <?php }?>

                            <form id="navbar-search" class="navbar-form navbar-left" method="post" action="forum.php">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search Posts" name="filter">
                                    <div class="input-group-btn">
                                        <button class="btn btn-default" type="submit">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </ul>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if (!isset($_SESSION['signed_in'])) {?>
                            <li><a href="signIn.php"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
                            <li><a href="registerUser.php"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                        <?php } else if(isset($_SESSION['signed_in'])) {?>
                            <li><a href="inbox.php"><span class="nav-envelope glyphicon glyphicon-envelope"></a></li>
                            <li><p class="navbar-brand pull-right hidden-xs"><?php if (isset($_SESSION['signed_in'] )) { echo 'Hello '.$_SESSION['firstName'].'!';}?></p></li>
                            <li><a href="logout.php"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                        <?php }?>
                    </ul>
                </div>
            </div>
        </nav>

        <div id="content" class="col-xs-12 col-sm-9 col-md-12 col-lg-12">



