<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Salford Wine Forum - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container">

    <div class="row">

        <!-- collapsing navbar -->
        <nav class="navbar navbar-inverse navbar-static-top">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-right">
                <?php if (!isset($_SESSION['signed_in'])) {?>
                    <button type="button" id ="sign-in-button" class="pull-right"><a href="signIn.php" class="navbar-brand">Sign In</a></button>
                <?php } else if(isset($_SESSION['signed_in'])) {?>
                    <button type="button" id ="sign-in-button" class="pull-right"><a href="logout.php" class="navbar-brand">Sign Out</a></button>
                <?php }?>
                </div>

                <p class="navbar-brand pull-left col-xs-5 col-md-5">Salford Wine Forum</p>
                <p class="navbar-brand pull-right hidden-xs"><?php if (isset($_SESSION['signed_in'] )) { echo 'Hello '.$_SESSION['firstName'].'!';}?></p>
            </div>

            <div class="container">
                <div class="navbar-collapse collapse" id="navbar">
                    <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
                        <ul class="nav navbar_default nav-stacked">
                            <li><a href="index.php">Home</a></li>
                            <li><a href="about.php">About</a></li>
                            <li><a href="forum.php">Forum</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <!-- V2-->
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Salford Meds Forum</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <div id="hover-link">
                        <ul class="nav navbar-nav">
                            <li><a href="index.php">Home</a></li>
                            <li><a href="about.php">About</a></li>
                            <li><a href="forum.php">Forum</a></li>
                            <li><a href="#">Page 3</a></li>
                        </ul>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if (!isset($_SESSION['signed_in'])) {?>
                            <li><a href="signIn.php"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
                            <li><a href="registerUser.php"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                        <?php } else if(isset($_SESSION['signed_in'])) {?>
                            <li><p class="navbar-brand pull-right hidden-xs"><?php if (isset($_SESSION['signed_in'] )) { echo 'Hello '.$_SESSION['firstName'].'!';}?></p></li>
                            <li><a href="logout.php"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                        <?php }?>
                    </ul>
                </div>
            </div>
        </nav>

        <div id="content" class="col-xs-12 col-sm-9 col-md-12 col-lg-12">



