<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <img src="images/new_uos_logo.jpg" alt="Salford University" />
                    <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>

            </div>
        </div>


    <div class="row">

        <!-- collapsing navbar -->
        <nav class="navbar navbar-inverse navbar-static-top">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Menu</a>
            </div>

            <div class="container">
                <div class="navbar-collapse collapse" id="navbar">
                    <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
                        <ul class="nav navbar_default nav-stacked">
                            <li><a href="index.php">Home</a></li>
                            <li><a href="about.php">About</a></li>
                            <li><a href="page1.php">Page1</a></li>
                            <li><a href="converter.php">Converter</a></li>
                            <li><a href="calculator.php">Calculator</a></li>
                            <li><a href="persistence.php">Persistence</a></li>
                            <li><a href="querystring.php">Query</a></li>
                            <li><a href="studentISv1.php">Students</a></li>
                            <li><a href="shop.php">Shop</a></li>
                            <li><a href="logout.php">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </nav>

        <!-- content -->

<!--        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">-->
<!--            <ul class="nav navbar_default nav-stacked">-->
<!--                <li><a href="index.php">Home</a></li>-->
<!--                <li><a href="about.php">About</a></li>-->
<!--                <li><a href="page1.php">Page1</a></li>-->
<!--                <li><a href="converter.php">Converter</a></li>-->
<!--            </ul>-->
<!--       </div>-->

    <div id="content" class="col-xs-6 col-sm-9 col-md-12">



